// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID           pgtype.UUID
	Amount       float64
	Type         string
	AccountLast4 pgtype.Text
	Merchant     pgtype.Text
	Name         pgtype.Text
	ReferenceID  pgtype.Text
	OccurredAt   pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
}
