// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthIntegration struct {
	ID           pgtype.UUID
	Provider     string
	Email        string
	AccessToken  string
	RefreshToken string
	TokenType    pgtype.Text
	Expiry       pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	UserID       pgtype.UUID
}

type SyncState struct {
	ID            pgtype.UUID
	Provider      string
	Email         string
	LastMessageID pgtype.Text
	UpdatedAt     pgtype.Timestamp
	UserID        pgtype.UUID
}

type Transaction struct {
	ID           pgtype.UUID
	Amount       float64
	Type         string
	AccountLast4 pgtype.Text
	Merchant     pgtype.Text
	Name         pgtype.Text
	ReferenceID  pgtype.Text
	OccurredAt   pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	UserID       pgtype.UUID
}

type User struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamp
}
