// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_integration.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthIntegration = `-- name: CreateOAuthIntegration :one

INSERT INTO oauth_integrations (
    provider,
    email,
    access_token,
    refresh_token,
    token_type,
    expiry
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, provider, email, access_token, refresh_token, token_type, expiry, created_at, updated_at
`

type CreateOAuthIntegrationParams struct {
	Provider     string
	Email        string
	AccessToken  string
	RefreshToken string
	TokenType    pgtype.Text
	Expiry       pgtype.Timestamp
}

func (q *Queries) CreateOAuthIntegration(ctx context.Context, arg CreateOAuthIntegrationParams) (OauthIntegration, error) {
	row := q.db.QueryRow(ctx, createOAuthIntegration,
		arg.Provider,
		arg.Email,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenType,
		arg.Expiry,
	)
	var i OauthIntegration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Email,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.Expiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthIntegrationByEmail = `-- name: GetOAuthIntegrationByEmail :one

SELECT id, provider, email, access_token, refresh_token, token_type, expiry, created_at, updated_at
FROM oauth_integrations
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetOAuthIntegrationByEmail(ctx context.Context, email string) (OauthIntegration, error) {
	row := q.db.QueryRow(ctx, getOAuthIntegrationByEmail, email)
	var i OauthIntegration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Email,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.Expiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOAuthToken = `-- name: UpdateOAuthToken :exec

UPDATE oauth_integrations
SET
    access_token = $2,
    expiry = $3,
    updated_at = NOW()
WHERE email = $1
`

type UpdateOAuthTokenParams struct {
	Email       string
	AccessToken string
	Expiry      pgtype.Timestamp
}

func (q *Queries) UpdateOAuthToken(ctx context.Context, arg UpdateOAuthTokenParams) error {
	_, err := q.db.Exec(ctx, updateOAuthToken, arg.Email, arg.AccessToken, arg.Expiry)
	return err
}
