// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobRun = `-- name: CreateJobRun :exec
INSERT INTO job_runs (job_id, started_at, finished_at, status, message)
VALUES ($1, $2, $3, $4, $5)
`

type CreateJobRunParams struct {
	JobID      pgtype.UUID
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Status     string
	Message    pgtype.Text
}

func (q *Queries) CreateJobRun(ctx context.Context, arg CreateJobRunParams) error {
	_, err := q.db.Exec(ctx, createJobRun,
		arg.JobID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Status,
		arg.Message,
	)
	return err
}

const createScheduledJob = `-- name: CreateScheduledJob :one
INSERT INTO scheduled_jobs (user_id, name, job_type, enabled, schedule, job_config, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, job_type, enabled, schedule, job_config, last_run_at, next_run_at, occurrences_run, created_at
`

type CreateScheduledJobParams struct {
	UserID    pgtype.UUID
	Name      string
	JobType   string
	Enabled   bool
	Schedule  []byte
	JobConfig []byte
	NextRunAt pgtype.Timestamptz
}

func (q *Queries) CreateScheduledJob(ctx context.Context, arg CreateScheduledJobParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, createScheduledJob,
		arg.UserID,
		arg.Name,
		arg.JobType,
		arg.Enabled,
		arg.Schedule,
		arg.JobConfig,
		arg.NextRunAt,
	)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.JobType,
		&i.Enabled,
		&i.Schedule,
		&i.JobConfig,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.OccurrencesRun,
		&i.CreatedAt,
	)
	return i, err
}

const deleteScheduledJob = `-- name: DeleteScheduledJob :exec
DELETE FROM scheduled_jobs WHERE id = $1
`

func (q *Queries) DeleteScheduledJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduledJob, id)
	return err
}

const getDueJobs = `-- name: GetDueJobs :many
SELECT id, user_id, name, job_type, enabled, schedule, job_config, last_run_at, next_run_at, occurrences_run, created_at FROM scheduled_jobs
WHERE enabled = true
  AND next_run_at IS NOT NULL
  AND next_run_at <= now()
ORDER BY next_run_at ASC
`

func (q *Queries) GetDueJobs(ctx context.Context) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, getDueJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledJob
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.JobType,
			&i.Enabled,
			&i.Schedule,
			&i.JobConfig,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.OccurrencesRun,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobRunsByJobID = `-- name: GetJobRunsByJobID :many
SELECT id, job_id, started_at, finished_at, status, message FROM job_runs
WHERE job_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type GetJobRunsByJobIDParams struct {
	JobID pgtype.UUID
	Limit int32
}

func (q *Queries) GetJobRunsByJobID(ctx context.Context, arg GetJobRunsByJobIDParams) ([]JobRun, error) {
	rows, err := q.db.Query(ctx, getJobRunsByJobID, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobRun
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledJobByID = `-- name: GetScheduledJobByID :one
SELECT id, user_id, name, job_type, enabled, schedule, job_config, last_run_at, next_run_at, occurrences_run, created_at FROM scheduled_jobs
WHERE id = $1
`

func (q *Queries) GetScheduledJobByID(ctx context.Context, id pgtype.UUID) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, getScheduledJobByID, id)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.JobType,
		&i.Enabled,
		&i.Schedule,
		&i.JobConfig,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.OccurrencesRun,
		&i.CreatedAt,
	)
	return i, err
}

const getScheduledJobsByUserID = `-- name: GetScheduledJobsByUserID :many
SELECT id, user_id, name, job_type, enabled, schedule, job_config, last_run_at, next_run_at, occurrences_run, created_at FROM scheduled_jobs
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetScheduledJobsByUserID(ctx context.Context, userID pgtype.UUID) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, getScheduledJobsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledJob
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.JobType,
			&i.Enabled,
			&i.Schedule,
			&i.JobConfig,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.OccurrencesRun,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobRan = `-- name: MarkJobRan :exec
UPDATE scheduled_jobs
SET last_run_at     = $2,
    next_run_at     = $3,
    occurrences_run = occurrences_run + 1,
    enabled         = $4
WHERE id = $1
`

type MarkJobRanParams struct {
	ID        pgtype.UUID
	LastRunAt pgtype.Timestamptz
	NextRunAt pgtype.Timestamptz
	Enabled   bool
}

func (q *Queries) MarkJobRan(ctx context.Context, arg MarkJobRanParams) error {
	_, err := q.db.Exec(ctx, markJobRan,
		arg.ID,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.Enabled,
	)
	return err
}

const updateScheduledJob = `-- name: UpdateScheduledJob :one
UPDATE scheduled_jobs
SET name = $2, enabled = $3, schedule = $4, job_config = $5, next_run_at = $6
WHERE id = $1
RETURNING id, user_id, name, job_type, enabled, schedule, job_config, last_run_at, next_run_at, occurrences_run, created_at
`

type UpdateScheduledJobParams struct {
	ID        pgtype.UUID
	Name      string
	Enabled   bool
	Schedule  []byte
	JobConfig []byte
	NextRunAt pgtype.Timestamptz
}

func (q *Queries) UpdateScheduledJob(ctx context.Context, arg UpdateScheduledJobParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, updateScheduledJob,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Schedule,
		arg.JobConfig,
		arg.NextRunAt,
	)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.JobType,
		&i.Enabled,
		&i.Schedule,
		&i.JobConfig,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.OccurrencesRun,
		&i.CreatedAt,
	)
	return i, err
}
