// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_state.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncStateByEmail = `-- name: GetSyncStateByEmail :one

SELECT id, provider, email, last_message_id, updated_at, user_id
FROM sync_state
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetSyncStateByEmail(ctx context.Context, email string) (SyncState, error) {
	row := q.db.QueryRow(ctx, getSyncStateByEmail, email)
	var i SyncState
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Email,
		&i.LastMessageID,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const upsertSyncState = `-- name: UpsertSyncState :exec

INSERT INTO sync_state (
    provider,
    email,
    last_message_id
)
VALUES (
    $1, $2, $3
)
ON CONFLICT (email)
DO UPDATE
SET
    last_message_id = EXCLUDED.last_message_id,
    updated_at = NOW()
`

type UpsertSyncStateParams struct {
	Provider      string
	Email         string
	LastMessageID pgtype.Text
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertSyncState, arg.Provider, arg.Email, arg.LastMessageID)
	return err
}
