// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_state.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncStateByEmail = `-- name: GetSyncStateByEmail :one

SELECT id, provider, email, last_message_id, updated_at, user_id, status, error
FROM sync_state
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetSyncStateByEmail(ctx context.Context, email string) (SyncState, error) {
	row := q.db.QueryRow(ctx, getSyncStateByEmail, email)
	var i SyncState
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Email,
		&i.LastMessageID,
		&i.UpdatedAt,
		&i.UserID,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const getSyncStatus = `-- name: GetSyncStatus :one
SELECT status, error, updated_at
FROM sync_state
WHERE email = $1
`

type GetSyncStatusRow struct {
	Status    string
	Error     pgtype.Text
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) GetSyncStatus(ctx context.Context, email string) (GetSyncStatusRow, error) {
	row := q.db.QueryRow(ctx, getSyncStatus, email)
	var i GetSyncStatusRow
	err := row.Scan(&i.Status, &i.Error, &i.UpdatedAt)
	return i, err
}

const updateSyncStatus = `-- name: UpdateSyncStatus :exec
INSERT INTO sync_state (provider, email, status, error, updated_at)
VALUES ('gmail', $1, $2, $3, NOW())
ON CONFLICT (email)
DO UPDATE SET
    status = EXCLUDED.status,
    error = EXCLUDED.error,
    updated_at = NOW()
`

type UpdateSyncStatusParams struct {
	Email  string
	Status string
	Error  pgtype.Text
}

func (q *Queries) UpdateSyncStatus(ctx context.Context, arg UpdateSyncStatusParams) error {
	_, err := q.db.Exec(ctx, updateSyncStatus, arg.Email, arg.Status, arg.Error)
	return err
}

const upsertSyncState = `-- name: UpsertSyncState :exec

INSERT INTO sync_state (
    provider,
    email,
    last_message_id
)
VALUES (
    $1, $2, $3
)
ON CONFLICT (email)
DO UPDATE
SET
    last_message_id = EXCLUDED.last_message_id,
    updated_at = NOW()
`

type UpsertSyncStateParams struct {
	Provider      string
	Email         string
	LastMessageID pgtype.Text
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertSyncState, arg.Provider, arg.Email, arg.LastMessageID)
	return err
}
