// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (
    amount,
    type,
    account_last4,
    merchant,
    name,
    reference_id,
    occurred_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, amount, type, account_last4, merchant, name, reference_id, occurred_at, created_at
`

type CreateTransactionParams struct {
	Amount       float64
	Type         string
	AccountLast4 pgtype.Text
	Merchant     pgtype.Text
	Name         pgtype.Text
	ReferenceID  pgtype.Text
	OccurredAt   pgtype.Timestamp
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Amount,
		arg.Type,
		arg.AccountLast4,
		arg.Merchant,
		arg.Name,
		arg.ReferenceID,
		arg.OccurredAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Type,
		&i.AccountLast4,
		&i.Merchant,
		&i.Name,
		&i.ReferenceID,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many

SELECT id, amount, type, account_last4, merchant, name, reference_id, occurred_at, created_at
FROM transactions
ORDER BY occurred_at DESC
`

func (q *Queries) GetTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Type,
			&i.AccountLast4,
			&i.Merchant,
			&i.Name,
			&i.ReferenceID,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
