// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionsByUserID = `-- name: CountTransactionsByUserID :one
SELECT COUNT(*)
FROM transactions
WHERE user_id = $1
`

func (q *Queries) CountTransactionsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (
    user_id,
    amount,
    type,
    account_last4,
    merchant,
    name,
    reference_id,
    occurred_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (reference_id)
DO NOTHING
`

type CreateTransactionParams struct {
	UserID       pgtype.UUID
	Amount       float64
	Type         string
	AccountLast4 pgtype.Text
	Merchant     pgtype.Text
	Name         pgtype.Text
	ReferenceID  pgtype.Text
	OccurredAt   pgtype.Timestamp
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.Exec(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.AccountLast4,
		arg.Merchant,
		arg.Name,
		arg.ReferenceID,
		arg.OccurredAt,
	)
	return err
}

const getTransactionsByUserID = `-- name: GetTransactionsByUserID :many
SELECT id, amount, type, account_last4, merchant, name, reference_id, occurred_at, created_at, user_id
FROM transactions
WHERE user_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsByUserIDParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetTransactionsByUserID(ctx context.Context, arg GetTransactionsByUserIDParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Type,
			&i.AccountLast4,
			&i.Merchant,
			&i.Name,
			&i.ReferenceID,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
