// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, color, is_system)
VALUES ($1, $2, $3, false)
RETURNING id, user_id, name, color, is_system, created_at
`

type CreateCategoryParams struct {
	UserID pgtype.UUID
	Name   string
	Color  string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.UserID, arg.Name, arg.Color)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const createCategoryRule = `-- name: CreateCategoryRule :one
INSERT INTO category_rules (category_id, keyword)
VALUES ($1, $2)
RETURNING id, category_id, keyword, created_at
`

type CreateCategoryRuleParams struct {
	CategoryID pgtype.UUID
	Keyword    string
}

func (q *Queries) CreateCategoryRule(ctx context.Context, arg CreateCategoryRuleParams) (CategoryRule, error) {
	row := q.db.QueryRow(ctx, createCategoryRule, arg.CategoryID, arg.Keyword)
	var i CategoryRule
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Keyword,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
  AND user_id IS NOT NULL
  AND is_system = false
`

func (q *Queries) DeleteCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteCategoryRule = `-- name: DeleteCategoryRule :exec
DELETE FROM category_rules
WHERE id = $1
`

func (q *Queries) DeleteCategoryRule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategoryRule, id)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, user_id, name, color, is_system, created_at
FROM categories
WHERE user_id IS NULL
   OR user_id = $1
ORDER BY is_system DESC, name ASC
`

func (q *Queries) GetAllCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getAllCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRulesForUser = `-- name: GetAllRulesForUser :many
SELECT cr.id, cr.category_id, cr.keyword, cr.created_at
FROM category_rules cr
JOIN categories c ON c.id = cr.category_id
WHERE c.user_id IS NULL
   OR c.user_id = $1
`

func (q *Queries) GetAllRulesForUser(ctx context.Context, userID pgtype.UUID) ([]CategoryRule, error) {
	rows, err := q.db.Query(ctx, getAllRulesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryRule
	for rows.Next() {
		var i CategoryRule
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Keyword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, user_id, name, color, is_system, created_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryRules = `-- name: GetCategoryRules :many
SELECT id, category_id, keyword, created_at
FROM category_rules
WHERE category_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetCategoryRules(ctx context.Context, categoryID pgtype.UUID) ([]CategoryRule, error) {
	rows, err := q.db.Query(ctx, getCategoryRules, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryRule
	for rows.Next() {
		var i CategoryRule
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Keyword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUncategorizedTransactions = `-- name: GetUncategorizedTransactions :many
SELECT id, amount, type, account_last4, merchant, name, reference_id, occurred_at, created_at, user_id, category_id
FROM transactions
WHERE user_id = $1
  AND category_id IS NULL
ORDER BY occurred_at DESC
`

func (q *Queries) GetUncategorizedTransactions(ctx context.Context, userID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getUncategorizedTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Type,
			&i.AccountLast4,
			&i.Merchant,
			&i.Name,
			&i.ReferenceID,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UserID,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT
  t.id, t.user_id, t.amount, t.type, t.account_last4,
  t.merchant, t.name, t.reference_id, t.occurred_at, t.created_at,
  t.category_id,
  c.name  AS category_name,
  c.color AS category_color
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1
ORDER BY t.occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

type ListTransactionsByUserRow struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Amount        float64
	Type          string
	AccountLast4  pgtype.Text
	Merchant      pgtype.Text
	Name          pgtype.Text
	ReferenceID   pgtype.Text
	OccurredAt    pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	CategoryID    pgtype.UUID
	CategoryName  pgtype.Text
	CategoryColor pgtype.Text
}

func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]ListTransactionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByUserRow
	for rows.Next() {
		var i ListTransactionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.AccountLast4,
			&i.Merchant,
			&i.Name,
			&i.ReferenceID,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionCategory = `-- name: SetTransactionCategory :exec
UPDATE transactions
SET category_id = $2
WHERE id = $1
`

type SetTransactionCategoryParams struct {
	ID         pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) SetTransactionCategory(ctx context.Context, arg SetTransactionCategoryParams) error {
	_, err := q.db.Exec(ctx, setTransactionCategory, arg.ID, arg.CategoryID)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, color = $3
WHERE id = $1
  AND user_id IS NOT NULL
  AND is_system = false
RETURNING id, user_id, name, color, is_system, created_at
`

type UpdateCategoryParams struct {
	ID    pgtype.UUID
	Name  string
	Color string
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.Color)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}
