// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_state.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncStateByEmail = `-- name: GetSyncStateByEmail :one
SELECT id, provider, email, updated_at, user_id, status, error, history_id
FROM sync_state
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetSyncStateByEmail(ctx context.Context, email string) (SyncState, error) {
	row := q.db.QueryRow(ctx, getSyncStateByEmail, email)
	var i SyncState
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Email,
		&i.UpdatedAt,
		&i.UserID,
		&i.Status,
		&i.Error,
		&i.HistoryID,
	)
	return i, err
}

const getSyncStatus = `-- name: GetSyncStatus :one
SELECT status, error, updated_at
FROM sync_state
WHERE email = $1
`

type GetSyncStatusRow struct {
	Status    string
	Error     pgtype.Text
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) GetSyncStatus(ctx context.Context, email string) (GetSyncStatusRow, error) {
	row := q.db.QueryRow(ctx, getSyncStatus, email)
	var i GetSyncStatusRow
	err := row.Scan(&i.Status, &i.Error, &i.UpdatedAt)
	return i, err
}

const upsertSyncState = `-- name: UpsertSyncState :exec
INSERT INTO sync_state (provider, email, history_id)
VALUES ($1, $2, $3)
ON CONFLICT (email)
DO UPDATE SET
    history_id = EXCLUDED.history_id,
    updated_at = NOW()
`

type UpsertSyncStateParams struct {
	Provider  string
	Email     string
	HistoryID pgtype.Text
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertSyncState, arg.Provider, arg.Email, arg.HistoryID)
	return err
}
