// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionsByUserID = `-- name: CountTransactionsByUserID :one
SELECT COUNT(*)
FROM transactions t
WHERE t.user_id = $1
  AND ($2::uuid  IS NULL OR t.category_id = $2::uuid)
  AND ($3::text         IS NULL OR t.type = $3::text)
  AND ($4::timestamptz  IS NULL OR t.occurred_at >= $4::timestamptz)
  AND ($5::timestamptz    IS NULL OR t.occurred_at <= $5::timestamptz)
  AND ($6::float8 IS NULL OR t.amount >= $6::float8)
  AND ($7::float8 IS NULL OR t.amount <= $7::float8)
  AND ($8::text       IS NULL OR t.merchant ILIKE '%' || $8::text || '%'
                                               OR t.name     ILIKE '%' || $8::text || '%')
`

type CountTransactionsByUserIDParams struct {
	UserID     pgtype.UUID
	CategoryID pgtype.UUID
	Type       pgtype.Text
	From       pgtype.Timestamptz
	To         pgtype.Timestamptz
	MinAmount  pgtype.Float8
	MaxAmount  pgtype.Float8
	Search     pgtype.Text
}

func (q *Queries) CountTransactionsByUserID(ctx context.Context, arg CountTransactionsByUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByUserID,
		arg.UserID,
		arg.CategoryID,
		arg.Type,
		arg.From,
		arg.To,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (
    user_id,
    amount,
    type,
    account_last4,
    merchant,
    name,
    reference_id,
    occurred_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (reference_id)
DO NOTHING
`

type CreateTransactionParams struct {
	UserID       pgtype.UUID
	Amount       float64
	Type         string
	AccountLast4 pgtype.Text
	Merchant     pgtype.Text
	Name         pgtype.Text
	ReferenceID  pgtype.Text
	OccurredAt   pgtype.Timestamp
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.Exec(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.AccountLast4,
		arg.Merchant,
		arg.Name,
		arg.ReferenceID,
		arg.OccurredAt,
	)
	return err
}

const getTransactionsByUserID = `-- name: GetTransactionsByUserID :many
SELECT
  t.id, t.user_id, t.amount, t.type, t.account_last4,
  t.merchant, t.name, t.reference_id, t.occurred_at, t.created_at,
  t.category_id,
  c.name  AS category_name,
  c.color AS category_color
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1
  AND ($4::uuid IS NULL OR t.category_id = $4::uuid)
  AND ($5::text        IS NULL OR t.type = $5::text)
  AND ($6::timestamptz IS NULL OR t.occurred_at >= $6::timestamptz)
  AND ($7::timestamptz   IS NULL OR t.occurred_at <= $7::timestamptz)
  AND ($8::float8 IS NULL OR t.amount >= $8::float8)
  AND ($9::float8 IS NULL OR t.amount <= $9::float8)
  AND ($10::text      IS NULL OR t.merchant ILIKE '%' || $10::text || '%'
                                              OR t.name     ILIKE '%' || $10::text || '%')
ORDER BY t.occurred_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsByUserIDParams struct {
	UserID     pgtype.UUID
	Limit      int32
	Offset     int32
	CategoryID pgtype.UUID
	Type       pgtype.Text
	From       pgtype.Timestamptz
	To         pgtype.Timestamptz
	MinAmount  pgtype.Float8
	MaxAmount  pgtype.Float8
	Search     pgtype.Text
}

type GetTransactionsByUserIDRow struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Amount        float64
	Type          string
	AccountLast4  pgtype.Text
	Merchant      pgtype.Text
	Name          pgtype.Text
	ReferenceID   pgtype.Text
	OccurredAt    pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	CategoryID    pgtype.UUID
	CategoryName  pgtype.Text
	CategoryColor pgtype.Text
}

func (q *Queries) GetTransactionsByUserID(ctx context.Context, arg GetTransactionsByUserIDParams) ([]GetTransactionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByUserID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Type,
		arg.From,
		arg.To,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByUserIDRow
	for rows.Next() {
		var i GetTransactionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.AccountLast4,
			&i.Merchant,
			&i.Name,
			&i.ReferenceID,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
