name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ contains(github.event.head_commit.message, 'deploy:backend') || contains(github.event.head_commit.message, 'deploy:all') }}
    environment: Production

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: FinanceManager/backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build Backend
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./server ./cmd/server
          ls -lah ./server
      - name: Verify From Workspace Root
        working-directory: .
        run: |
          pwd
          ls -la
          find . -name server -type f
      - name: Copy Binary
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          source: |
            PersonalManager/FinanceManager/backend/server
            PersonalManager/FinanceManager/backend/Makefile
            PersonalManager/FinanceManager/backend/internal/db/migrations
          target: "/home/ubuntu/deploy"

      - name: Restart Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            mkdir -p /home/ubuntu/app

            cp /home/ubuntu/deploy/PersonalManager/FinanceManager/backend/server /home/ubuntu/app/server
            cp /home/ubuntu/deploy/PersonalManager/FinanceManager/backend/Makefile /home/ubuntu/app/Makefile
            cp -r /home/ubuntu/deploy/PersonalManager/FinanceManager/backend/internal/db/migrations /home/ubuntu/app/migrations

            chmod +x /home/ubuntu/app/server

            make migrate-up

            sudo systemctl restart financemanager
            sudo systemctl status financemanager --no-pager